### ISSUE TITLE
Allow to add custom labels to a SLO

### ISSUE THREAD

**Issue by kyledakid** [slok/sloth#110]
Hi, thanks for creating this awesome repo. I'm wondering that is there a way to add a custom label to a specific SLO ?

![image](https://user-images.githubusercontent.com/12691265/124539025-e5d5c080-de46-11eb-9e51-d2ec6e4ed738.png)

 Or can you please make sloth to generate the 'description' ?
![image](https://user-images.githubusercontent.com/12691265/124539137-13226e80-de47-11eb-89ef-0399c88764bd.png)

I need to show the details of SLO on Dashboard. For example, for LatencyP90 SLO, I want to show that we're setting the second as '4s', and want to show this '4s' on Dashboard, rather than just the Objective of 90%

I love your work @slok

**Comment by slok** [comment]
Hi @kyledakid!

Thanks for the kind words!! :bow: :tada: 

You already can add labels to your SLO! Check `slos[].labels`:

- `Prometheus/v1`: https://github.com/slok/sloth/tree/main/pkg/prometheus/api/v1#type-slo
- K8s `sloth.slok.dev/v1/PrometheusServiceLevel`: https://github.com/slok/sloth/tree/main/pkg/kubernetes/api/sloth/v1#type-slo

An example:

https://github.com/slok/sloth/blob/32458b3aebc4e3986158ff201ca00498ed530fa5/examples/kubernetes-apiserver.yml#L29-L30

Regarding the description, descriptions normally are big text fields, ending that on a label could be dangerous for Prometheus. for now I would like to avoid that :smile:

**Comment by kyledakid** [comment]
Beautifullll, thanks @slok . This can be closed
