### ISSUE TITLE
support for victoriaMetrics

### ISSUE THREAD

**Issue by Sunn-y-Arora** [slok/sloth#136]
Hi @slok , is there any plan to support [vm](https://docs.victoriametrics.com/vmagent.html)  ,
the the architecture is almost similar. (happy to contribute 😄  )

tried out sloth with prom worked seemingly, for our prod setup, we're using vm and at the moment sloth only supports prom.

**Comment by slok** [comment]
Hi @Sunn-y-Arora!

I'm not familiar with Victoria metrics nor VM agent and maybe I'm mistaken, but, could the current Prom rules that Sloth generates be compatible with [vmalert](https://docs.victoriametrics.com/vmalert.html)?

**Comment by slok** [comment]
Closing the issue, we can reopen it if required.

Many thanks!
