### ISSUE TITLE
Thanos Ruler and duplicate series

### ISSUE THREAD

**Issue by nextrevision** [slok/sloth#153]
Thanks for open sourcing such a valuable tool, it's been really easy to extend and get up and running!

I'm running into an issue using sloth with prometheus and thanos. Prometheus is installed and managed by the prometheus-operator and my thanos ruler is created using the `ThanosRuler` CRD. The retention time for my prometheus metrics on the prometheus instance is intentionally low at 6h since the thanos sidecar exports to s3 periodically.

I suspect this was causing my 30d burn metrics to be skewed since prometheus cannot query itself for 30d in the past due to the 6h retention. I have tried installing the SLO as a PrometheusRule that is instead evaluated by Thanos Ruler since it has access to the other thanos components to query for 30+ days in the past.

I'm now getting the following error when evaluating the `slo:current_burn_rate:ratio` metric:

```
Error executing query: found duplicate series for the match group {sloth_id="sloth-sample-http-availability-sloth-sample", sloth_service="sloth-sample", sloth_slo="http-availability-sloth-sample"} on the right hand-side of the operation: [{__name__="slo:error_budget:ratio", sloth_id="sloth-sample-http-availability-sloth-sample", sloth_service="sloth-sample", sloth_slo="http-availability-sloth-sample"}, {__name__="slo:error_budget:ratio", prometheus="prometheus/prometheus-operator-prometheus", sloth_id="sloth-sample-http-availability-sloth-sample", sloth_service="sloth-sample", sloth_slo="http-availability-sloth-sample"}];many-to-many matching not allowed: matching labels must be unique on one side
```

Running one of the metric queries directly I see two sets of data returned, which explains the error:
```
slo:sli_error:ratio_rate5m{sloth_id="sloth-sample-http-availability-sloth-sample",sloth_service="sloth-sample",sloth_slo="http-availability-sloth-sample"}
```

```
slo:sli_error:ratio_rate5m{prometheus="prometheus/prometheus-operator-prometheus", sloth_id="sloth-sample-http-availability-sloth-sample", sloth_service="sloth-sample", sloth_slo="http-availability-sloth-sample", sloth_window="5m"}
slo:sli_error:ratio_rate5m{sloth_id="sloth-sample-http-availability-sloth-sample", sloth_service="sloth-sample", sloth_slo="http-availability-sloth-sample", sloth_window="5m"}
```

Sure enough if I add an additional label filter to the `slo:current_burn_rate:ratio` metric, `prometheus!="prometheus/prometheus-operator-prometheus"`, it evaluates just fine.

This is due to Thanos Ruler and Prometheus both loading and evaluating the PrometheusRule, which I wasn't expecting. Is there any way to add a label filter to some of the queries or a better way to run sloth with thanos?

**Comment by slok** [comment]
Hi @nextrevision!

Thanks!
 
If I understood the problem correctly, Once Prometheus stops handling the rules and Thanos is the only one processing them, eventually, the Sloth metrics created by Prometheus will disappear, however that would be too long.

After Thanos is the only one processing the Sloth-generated rules, I suggest you change the SLO name, this will change the ID and it will be a new one that will not collide with the previous one.

e.g: `http-availability-sloth-sample` to `http-availability-sloth-sample-v2`, like a new iteration of the SLO.

Regarding Thanos and prometheus-operator, I don't use Thanos myself, however, I guess you already know/seen that the K8s labels you use on Sloth's CR, will be set on the generated prometheus-operator CR rules, so, having different rule selectors for the [Prometheus `RuleSelector`](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec) and [Thanos `RuleSelector`](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#thanosrulerspec) rules should be enough.

Hope this helps!

**Comment by nextrevision** [comment]
Thanks for the response and that helps a ton! I somehow missed the ruleSelector in the prometheus spec. That coupled with the `v2` change worked wonderfully.

Thanks again!
