### ISSUE TITLE
helm linting error on variables

### ISSUE THREAD

**Issue by hieulengoc** [slok/sloth#156]
Hi,
I use k8s template to generate the prometheusRules, unfortunately the generated yaml file fails at linting:

[ERROR] templates/: parse error at (monitoring/templates/prometheusSlothRules.yaml:183): undefined variable "$labels"

with the line:

title: (page) {{$labels.sloth_service}} {{$labels.sloth_slo}} SLO error budget

because helm's treating the {{ }} as helm variables. Should we escape this one? Or is there a way to work around?
Thanks!
Best,
Hieu

**Comment by slok** [comment]
Hi @hieulengoc!

I would like to avoid coupling Prometheus to specific tools like Helm. Maybe you could generate the YAML files and process the generated file with some script using `sed` or similar and replace the problematic strings/characters with some that scapes them.

Would this work for you?

Another solution (knowing that you use helm) would be using Sloth as a Kubernetes controller and set the SLOs with the CRDs.

**Comment by hieulengoc** [comment]
Hi @slok,

Thank you very much for the quick reply. I know I could use sed to modify the yaml but I want to avoid it (forward compatibility if you have changes in the future).

But you are right, I should not couple Prometheus to Helm, I think the better approach for me would be separating Sloth generation and run kubectl apply -f generated_file.yaml from the pipeline without embedding it into the monitoring helm chart.

Running Sloth as controller is also an option but with lower prio, we are very limited and restricted in term of resources and additional components.

Thank you very much for this awesome piece of software!
Best.
