### ISSUE TITLE
how to use it on windows dev box

### ISSUE THREAD

**Issue by iheng** [slok/sloth#185]
Hi,
I'm new to  Prometheus and grafana.  I'd like to know what's require steps to using this tool. I have read the document. But I still have no clue . how to use it.
A little background my application. I'm using AWS hosted Prometheus server, Grafana is currently running local windows dev box.
K8s is running on AWS EKS.

Thanks,
Heng

**Comment by slok** [comment]
Hi @iheng!

Check this issue https://github.com/slok/sloth/issues/135 Somebody had the same option and I couldn't reproduce it, I could use Sloth on windows correctly.

Check if the downloaded spec is not empty, or you don't have permission to load it.

Best.

**Comment by iheng** [comment]
Thanks.

**Comment by slok** [comment]
Closing, if you have any other problems, please open a new issue.
