### ISSUE TITLE
error: "generate" command failed: invalid spec, could not load with any of the supported spec types

### ISSUE THREAD

**Issue by joegalley** [slok/sloth#187]
I get the error in the issue title when running the `generate` command for an OpenSLO formatted file. I'm using the Windows executable for [v0.7.0](https://github.com/slok/sloth/releases/download/v0.8.0/sloth-windows-amd64.exe).

I'm using this [example file](https://github.com/slok/sloth/blob/main/examples/openslo-getting-started.yml) as input.

I run this command (from [here](https://sloth.dev/specs/openslo/)):

```
./sloth-windows-amd64.exe generate -i ./examples/openslo-getting-started.yml -o /tmp/openslo-getting-started.yml
```

and get this error:

```
INFO[0000] SLI plugins loaded                            plugins=0 svc=storage.FileSLIPlugin version=v0.7.0
error: "generate" command failed: invalid spec, could not load with any of the supported spec types
```

So it looks like I'm missing a plugin, but I don't see any OpenSLO plugins in the [plugin repo](https://github.com/slok/sloth-common-sli-plugins/tree/main/plugins). Do we need a plugin for OpenSLO? Also the function of the plugins aren't clear to me - "[can be referenced as an SLI on the SLO specs and will return a raw SLI type](https://sloth.dev/usage/plugins/)" - what does this mean exactly?

**Comment by slok** [comment]
Hi @joegalley!

I would say that is not related to the plugins. OpenSLO spec doesn't support Sloth's SLI plugin system.

Check this issue https://github.com/slok/sloth/issues/135 Somebody had the same issue and I couldn't reproduce it, I could use Sloth on windows correctly.

Check if the downloaded spec is not empty, or you don't have permission to load it.

Regading whats an SLI plugin. Plugins are a way of abstracting the SLI (query) from the user, like when in programming you use a library and you don't need to know the underneath implementation. This would be something similar but for SLIs.

For example one person/team creates the plugin, another person/team uses it by referencing the plugin. E.g:

Normally you could set this on the spec:

```
    sli:
      events:
        error_query: sum(rate(http_request_duration_seconds_count{job="myservice",code=~"(5..|429)"}[{{.window}}]))
        total_query: sum(rate(http_request_duration_seconds_count{job="myservice"}[{{.window}}]))
```

Having a plugin for that SLI. you could use like this:

```
sli:
  plugin:
    id: "my-company/services/availability"
```

This abstracts the queries and gains things like:
- Could create standards across the company.
- Have a repository/index of plugins for [common used applications](https://github.com/slok/sloth-common-sli-plugins)
- Boost best practices on queries by having people with a lot of Prometheus knowledge maintain the plugins
- Centralizes the SLI queries (update in one place, deliver to all the plugin users).


Best.

**Comment by stephanecazeaux** [comment]
Hello

I encounter the same issue on windows. The problem is simply related to carriage return encoding:

* with CRLF it fails
* with LF it's OK

I have not digged into the code, but it might be possible to fix that.

**Comment by slok** [comment]
Thanks for the info @stephanecazeaux, it's very valuable!

**Comment by joegalley** [comment]
@stephanecazeaux This fixed my issue, thank you
