### ISSUE TITLE
Create ideal burn rate on Grafana month burn down chart

### ISSUE THREAD

**Issue by slok** [slok/sloth#216]
This issue that comes from https://github.com/slok/sloth/issues/196#issuecomment-962567986

cc/ @itkq

**Comment by slok** [comment]
Implemented on the [5th](https://grafana.com/api/dashboards/14348/revisions/5/download) revision of [SLOs Grafana dashboad](https://grafana.com/grafana/dashboards/14348/revisions):

![Screenshot_20211206_133453](https://user-images.githubusercontent.com/128204/144848970-defe8967-4d4d-4fd7-9a77-95bf44e5f02d.png)


![Screenshot_20211206_133550](https://user-images.githubusercontent.com/128204/144848993-c5ca7ce1-72c4-4e0f-ad36-c2a6440eeca2.png)

**Comment by itkq** [comment]
Super cool!
