### ISSUE TITLE
There is no 'description' field in Grafana. Where should it be appearing?

### ISSUE THREAD

**Issue by VCuzmin** [slok/sloth#219]
Where should I see the description from the **_slos_** object? (the circled area from the image below)

![image](https://user-images.githubusercontent.com/40390118/145408972-4700f192-74d1-45f1-bf2a-c0c1adbfd01c.png)

The description doesn't show up in Grafana for instance (see the image below)

![image](https://user-images.githubusercontent.com/40390118/145409679-1c83b429-44b8-4d42-a59a-ba1ed0159b52.png)

Where should I see the 'description' field?

Thanks in advance for helping me!

**Comment by slok** [comment]
Hi @VCuzmin!

Description field will not appear on the Grafana dashboard, that field is the documentation for the SLO that can be checked by humans on the specs directly, or loaded specs and parsed them by a program for your own use case.

**Comment by VCuzmin** [comment]
Ok. I got it. Thank you for your answer!
