### ISSUE TITLE
Remove sloth_window from alert expression

### ISSUE THREAD

**Issue by tokheim** [slok/sloth#240]
Below is a graph of the alert expression for an ongoing alert we had

![image](https://user-images.githubusercontent.com/867076/151660683-e2cadd18-e499-4aa6-beca-4849fc2936e6.png)

it appears like the `sloth_window` label is part of the generated alert, and that the label changes value depending on whether the quick or slow alerting conditions are triggered. This can cause a lot of noise with resolving and re-firing alerts. So in the example above, essentially the same alert fired about 6 times over an hour.

I would propose to change the alerting expression a bit to actively drop the `sloth_window` label, to avoid excessive firings of the same alert. A proposal for a new alerting expression would be something like

```
(
  max(
    slo:sli_error:ratio_rate5m{sloth_id="a",sloth_service="b",sloth_slo="c"} > (13.44 * 0.01)
  ) without (sloth_window) and
  max(
    slo:sli_error:ratio_rate1h{sloth_id="a",sloth_service="b",sloth_slo="c"} > (13.44 * 0.01)
  ) without (sloth_window)
) or
(
  max(
     slo:sli_error:ratio_rate30m{sloth_id="a",sloth_service="b",sloth_slo="c"} > (3.5 * 0.01)
  ) without (sloth_window) and
  max(
     slo:sli_error:ratio_rate6h{sloth_id="a",sloth_service="b",sloth_slo="c"} > (3.5 * 0.01)
  ) without (sloth_window)
)
```

In the expression, `max` should never aggregate multiple metrics. But even if it did it would take the highest error ratio, which seems like a good pessimistic approach.

Would be happy to try to contribute a PR if you think the change makes sense

**Comment by tokheim** [comment]
Hi @slok,

Any interest in this if I do a PR, or is maybe the issue here not well enough explained for you?

**Comment by evgkrsk** [comment]
Wish to have this fix, too.
