### ISSUE TITLE
Helm chart is non-functional without CRDs

### ISSUE THREAD

**Issue by evgkrsk** [slok/sloth#246]
sloth-0.4.1 chart gets CrashLoopBackOff-ed pod(s) with following log:

```
error: "kubernetes-controller" command failed: check for PrometheusServiceLevel CRD failed: could not list: the server could not find the requested resource (get prometheusservicelevels.sloth.slok.dev)%
```

Seems like there need for crds/ folder in chart archive with CRD manifest(s).

**Comment by forumsheth15** [comment]
I am facing the same issue. Did you find any solution for this? @evgkrsk

**Comment by evgkrsk** [comment]
I see three ways to resolve this issue:
1) Use high-level helm package manager (helmfile, helmsman, helmwave) to apply CRDs before sloth chart
2) Fork sloth chart and fix manifests
3) Make PR to sloth chart

At the moment, I use first method for myself.

**Comment by slok** [comment]
CRDs are now part of the chart in `>=v0.5.0` :rocket:

**Comment by evgkrsk** [comment]
Thanks!
