### ISSUE TITLE
Loki rules fail validation

### ISSUE THREAD

**Issue by jimethn** [slok/sloth#255]
LokiRuler supports PrometheusRule resources, but if I try to pass a Loki-format rule to sloth it fails with the error:

```
INFO[0000] Generating from Kubernetes Prometheus spec    version=sloth-helm-chart-0.4.0-13-g6341f64 window=30d
error: "generate" command failed: could not generate Kubernetes format rules: could not generate prometheus rules: invalid SLO group: Key: 'SLOGroup.SLOs[0].SLI.Events.ErrorQuery' Error:Field validation for 'ErrorQuery' failed on the 'prom_expr' tag
Key: 'SLOGroup.SLOs[0].SLI.Events.TotalQuery' Error:Field validation for 'TotalQuery' failed on the 'prom_expr' tag%  
```

The relevant section of an example that fails:

```
      sli:
        events:
          errorQuery: |
            sum(rate(
              {job="nginx-ingress"}
                | json
                | status >= 500
                | __error__ != "JSONParserErr"
            [{{.window}}]))
          totalQuery: |
            sum(rate(
              {job="nginx-ingress"}
                | json
                | __error__ != "JSONParserErr"
            [{{.window}}]))
```

Would it be possible to make the validator pass these rules, and/or add an option to disable the validation step?

**Comment by slok** [comment]
Hi @jimethn! thanks for the Issue.

What is your use case?

Sloth is focused on Prometheus and only supports [PromQL](https://prometheus.io/docs/prometheus/latest/querying/basics/), and will always check for valid PromQL rules. If I'm not mistaken, what you are suggesting, is [LogQL](https://grafana.com/docs/loki/latest/logql/), Sloth will not support it, so there shouldn't be on Sloth manifests.
