### ISSUE TITLE
Packaging sloth for arch linux

### ISSUE THREAD

**Issue by oliviermichaelis** [slok/sloth#266]
Hi @slok! :)

I would be interested in packaging sloth for arch linux via the AUR ([arch user repository](https://aur.archlinux.org/)).
Is that something you would like to see? Please let me know if you have any concerns!

**Comment by slok** [comment]
Hi @oliviermichaelis!

I'm an Arch user myself! :smile:  so if you would like to create an AUR package, would be just awesome :heart:

**Comment by oliviermichaelis** [comment]
Oh that's awesome! :heart: 

I've just published the [`sloth-bin`](https://aur.archlinux.org/packages/sloth-bin) package to the AUR.
Do you think it's worth mentioning that somwhere in the documentation?

**Comment by slok** [comment]
Awesome! :rocket: 

Sure, you can make a PR to the sloth docs: https://github.com/slok/sloth-website/blob/main/docs-src/introduction/install.md
