### ISSUE TITLE
Deploying Sloth through Helm

### ISSUE THREAD

**Issue by pcperera** [slok/sloth#283]
### Question

I use the below config to deploy **sloth-from-helm** application set. However the application set is not deployed. 

- Great if you can confirm below **repoURL**, **targetRevision** and **chart** are correct or not ? Intention is to use the latest https://github.com/slok/sloth/releases/tag/sloth-helm-chart-0.5.0 helm chart version.
- Where can I find documentation on any Helm parameters to be used ?

![image](https://user-images.githubusercontent.com/15628990/162112317-319eae03-5f96-4a5f-9eaa-cbe873facb93.png)

**Comment by slok** [comment]
Here you can see the URL in the [docs](https://sloth.dev/introduction/install/#kubernetes), however, seems right to me. Could you test it locally without ArgoCD?

Thanks!
