### ISSUE TITLE
helm chart missing tolerations

### ISSUE THREAD

**Issue by anwaramoon** [slok/sloth#287]
Hi, 

Helm chart deployment is missing tolerations. Can these be added please? Happy to submit a PR too.

https://github.com/slok/sloth/blob/main/deploy/kubernetes/helm/sloth/templates/deployment.yaml

**Comment by slok** [comment]
Hey @anwaramoon.

Non of the current users of Sloth had this need, however, happy to review the PR :)

**Comment by anwaramoon** [comment]
@slok Please review PR #319 to add tolerations.

**Comment by anwaramoon** [comment]
@slok  any chance for merging chart related PRs and release new version of helm chart soon? Thanks

**Comment by slok** [comment]
Done! apologies for the delay. Thanks for the patience and the PR :smile:

Fixed in #319.
