### ISSUE TITLE
Sloth page alerts vs ticket alerts

### ISSUE THREAD

**Issue by pcperera** [slok/sloth#305]
- What's the difference between Sloth page alert and ticket alert ?
- What is the more critical alert ?
- Can these alert type labels be changed to custom values (e.g.: warning and critical) ?

**Comment by pcperera** [comment]
Appreciate any input on this. Thanks.

**Comment by slok** [comment]
Hi @pcperera 

A good explanation is on the Google SRE workbook, [Alerting on SLOs chapter](https://sre.google/workbook/alerting-on-slos/).

Those names can't be changed, they are like that for uniformity with the vocabulary used around SLOs based on Google's framework, so it's a defacto standard.

Answered, so I'm closing the issue, if you have further questions regarding this please reopen it, thanks!

Best,
