### ISSUE TITLE
Sloth generate/validate commands fail

### ISSUE THREAD

**Issue by mo3athi** [slok/sloth#308]
Hi. I'm using docker for experimenting sloth, but when I try to validate/generate any of the default example files it fails!

Here's what I did exactly:

- `docker pull ghcr.io/slok/sloth `

- `docker run IMAGE_ID generate -i ./examples/getting-started.yml`

And this is the error I get from the previous command:
`error: "generate" command failed: stat ./examples/getting-started.yml: no such file or directory%`

_I'm using MacOS_

**Comment by slok** [comment]
Hi @mo3athi!

Examples are not part of the production image of Sloth, and you are not mounting into the container the example files.

You can try this:

```bash
git clone https://github.com/slok/sloth /tmp/sloth && docker run --rm -i -v /tmp/sloth:/tmp/sloth ghcr.io/slok/sloth generate -i /tmp/sloth/examples/getting-started.yml
```

**Comment by slok** [comment]
I will assume that has been solved :sweat:, please reopen if this is not the case.
