### ISSUE TITLE
slo on uptime metrics

### ISSUE THREAD

**Issue by LinTechSo** [slok/sloth#318]
Hi, 
How can I use uptime metrics in sloth sli syntax? 
because the common syntaxes that I see in examples include error_query and total_query, not just one query

**Comment by christianlafleur** [comment]
You can use up sli plugin

**Comment by slok** [comment]
Hey!

Indeed, as @christianlafleur sais, in this specific use case you can use [`sloth-common/prometheus/targets/availability` plugin](https://sloth.dev/sli-plugins/prometheus-targets-availability/).

On the other hand, if you want raw queries that return the SLI error ratio directly you can use [`raw SLI`](https://sloth.dev/examples/default/raw-sli/).

Closing the issue..., if you need something else, please reopen :smile:
