### ISSUE TITLE
OpenSLO Kubernetes compatiblity

### ISSUE THREAD

**Issue by druanoor** [slok/sloth#345]
Hi.

First of all, thank you for this amazing tool. We are planning on use it on our daily basis, but we also are very interested in using OpenSLO standard to write our SLOs.

Is it planned to be added Kubernetes support for this? I've read on the website that no until OpenSLO CRDs went live, but they are v1.0.0 already. So, any news?

**Comment by druanoor** [comment]
They moved to v1.0.0 [here](https://github.com/OpenSLO/OpenSLO/releases/tag/v1.0.0) and the CRDs are supposed to be embedded in this [oslo project](https://github.com/OpenSLO/oslo) but i couldn't find any "standalone" CRDs or client libraries

**Comment by slok** [comment]
Hey @druanoor,

Until OpenSLO offers official CRDs (with seems that don't), Sloth will not provide OpenSLO Kubernetes support. however, sloth has Kubernetes support with it's own CRDs if you need that.

Best,
