### ISSUE TITLE
Missing CPU Limit in Helm template

### ISSUE THREAD

**Issue by druanoor** [slok/sloth#352]
Hi.

CPU Limit is missing in the helm template, i opened a PR to fix this issue: https://github.com/slok/sloth/pull/351

**Comment by druanoor** [comment]
Also this PR from another user is moving resources values to values.yaml file: https://github.com/slok/sloth/pull/324

**Comment by evgkrsk** [comment]
@slok , can you review and merge these PRs, please?

**Comment by slok** [comment]
The CPU limits were removed on purpose ([1](https://home.robusta.dev/blog/stop-using-cpu-limits/), [2](https://www.youtube.com/watch?v=eBChCFD9hfs), ), CPU limits cause more harm than good. However, we are moving the resources to the values.yaml so anyone can put whatever want.

**Comment by slok** [comment]
Fixed in #324
