### ISSUE TITLE
Controller targeting multiple namespaces

### ISSUE THREAD

**Issue by mihaidraghici98** [slok/sloth#361]
Does Sloth support monitoring multiple namespaces?

I see there are two options
- specify the namespace, in this case only the specified namespace will be monitored
- do not specify the namespace, in this case the default will be to monitor all namespaces

**Comment by slok** [comment]
Hi @mihaidraghici98 

you are correct, those are the only options, those are the most common use cases, and adding more not-so-common use cases would be complex and harder to maintain, and isn't worth it in general, very few use cases need what you say.

Normally, if you need to target different namespaces with different Sloths, you would create N sloths and target SLOs using labels so each of them only reads the CRs that you want.

Best,
