### ISSUE TITLE
Suppress alerts in certain time ranges?

### ISSUE THREAD

**Issue by jayarjo** [slok/sloth#370]
It's more like a question, unless a feature like is not yet supported.

We need to suppress alerts in certain time ranges (non office hours basically). Is there a way to declare these somehow in Sloth config?

**Comment by slok** [comment]
Hi @jayarjo 

Sloth doesn't support this (IMHO this should be the responsibility of the notifier).

Maybe a better way of doing this would be using [`time_intervals`](https://prometheus.io/docs/alerting/latest/configuration/#time_interval) feature on alertmanager.

Let us know how you solve it! I'm sure that other people have this same problem :)
