### ISSUE TITLE
Maybe add successQuery?

### ISSUE THREAD

**Issue by jayarjo** [slok/sloth#372]
Currently in some cases (when generating a query for latency) we have to do total requests minus successful requests manually to acquire errorQuery, which is basically an extra unnecessary step. Sloth already has totalQuery and having a successQuery could do this calculation itself.

**Comment by slok** [comment]
Hey @jayarjo!

That would add a new option and will make the API more difficult for users. However, if you want to simplify your queries in those cases, people use the SLI [`Raw`](https://pkg.go.dev/github.com/slok/sloth@v0.6.0/pkg/prometheus/api/v1#SLIRaw) query form for that purpose.

Best,
