### ISSUE TITLE
Behaviour when complete service outage

### ISSUE THREAD

**Issue by mihaidraghici98** [slok/sloth#380]
Hello!

Does Sloth have a mechanism to include total service outages?

For example in a K8s deployment the pods might not exist at all or be excluded from the load balancer due to livenessProbe failing, thus the availability for the duration of incident being 0%.

I was trying to include such mechanism in the `sli.events` queries, but the 0% availability will be propagated to all windows and mess the SLI burn ratio (e.g. windows for 30d will be 0%, meaning a huge burn ratio).

Thanks!

**Comment by slok** [comment]
Hi @mihaidraghici98!

Sloth doesn't support that :/

I would suggest creating another SLO based on the Prometheus `up` metric. Even more, maybe you could play with the [Prometheus target SLI plugin](https://github.com/slok/sloth-common-sli-plugins/tree/main/plugins/prometheus/targets/availability).

Best,
