### ISSUE TITLE
unable to see Sloth SLO dashboard in Grafana

### ISSUE THREAD

**Issue by aishvaryaps** [slok/sloth#395]
@slok 
I have set up Prometheus and Grafana on the same VM . And on same VM i have set up Sloth and running the below command
![image](https://user-images.githubusercontent.com/48279639/193296200-773f2ff5-a413-46cf-b463-e698a11586bd.png)

now i am confused about next steps
can please anyone tell me how can i see SLO dashbaords in grafana.
Grafana has integrated with Prometheus

Do i have to copy paste generated prometheus yaml anywhere in prometheus ?

**Comment by slok** [comment]
Hi @aishvaryaps!

As @david-peters-aitch2o says, you should be able to load the generated Prometheus rules in your Prometheus using that syntax. For more information check [Prometheus docs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/).

Best!
