### ISSUE TITLE
Month error budget burn chart has wrong window

### ISSUE THREAD

**Issue by evalsocket** [slok/sloth#435]
Currently, few panel in dashboard use 32 days time window, It should be 30 days 

error: `execution: expanding series: the query time range exceeds the limit (query length: 776h1m9.796s, limit: 768h0m0s) (err-mimir-max-query-length). To adjust the related per-tenant limit, configure -store.max-query-length, or contact your service administrator.: details: `

**Comment by slok** [comment]
Hi @evalsocket!

This comes from `Month error budget burn chart` panel and is done to make sure we get the full month (although non-required data is filtered then). I guess that the error message you get there is from a Prometheus cloud vendor like AWS or a cortex installation with strict limits.

You can change the Grafana dashboard and change the `[31d:1h] range to a shorter window that adjusts to your needs/limits.

Best,
