### ISSUE TITLE
Helm chart tolerations misplacement

### ISSUE THREAD

**Issue by arouxAgicap** [slok/sloth#466]
Hi !
I'm using argocd application sets to deploy sloth on all my kubernetes clusters and i'm encountering an issue deploying them. 
I want sloth to deployed on the same node as prometheus to not interfere with application deployment and i'm usually using tolerations for this purpose. when trying to synchronize the application set with the current helm chart version, I got the following issue :
```
#error validating data: ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "tolerations" in io.k8s.api.core.v1.Container
```

I took a look at the deployment.yaml and I saw that the toleration part is not where it's supposed to be. Instead of being at `Deployment.spec.template.spec.containers[0]`, it should be located at `Deployment.spec.template.spec` like node selector and affinity/anti-affinity.

I suspect that right now, the tolerations are just not working. And even if it is working, it does not seems to me, to be a good idea to allow containers of the same deployment to be deployed on different node.

Could you fix that or would you rather me to fix it ?

I can provide more information if you want

**Comment by klubi** [comment]
Sorry to open this issue, but 0.7.0 helm chart is still having tolerations misplaced.
PR that was opened to fix this is open. Would be nice if it was reviewed and merged.
