### ISSUE TITLE
Multi-arch images

### ISSUE THREAD

**Issue by paulfantom** [slok/sloth#73]
Would it be possible to publish multi-arch images? I am mostly interested in the ability to specify one image string that underneath would translate to the correct image for AMD64 or ARM64. 

For example prometheus-operator is publishing such images with the following script: https://github.com/prometheus-operator/prometheus-operator/blob/master/scripts/push-docker-image.sh. Or even better one can be found in kube-rbac-proxy repo: https://github.com/brancz/kube-rbac-proxy/blob/master/scripts/publish.sh

**Comment by slok** [comment]
Hey @paulfantom!

I just added support for multi-arch images. From now on, you will have available on `latest`, tagged releases, and also each PR merge and push on the `main` branch, e.g:

- `docker pull slok/sloth:v0.3.1`
- `docker pull slok/sloth:latest`

**Comment by paulfantom** [comment]
Everything seems to be working just fine on ARM64:
```
$ kubectl describe pod sloth-7b78ffd46d-259pt
Name:         sloth-7b78ffd46d-259pt
Namespace:    monitoring
...
Start Time:   Mon, 14 Jun 2021 10:56:42 +0200
...
Status:       Running
...
Containers:
  sloth:
    Container ID:  containerd://35ee4283bdd95c54b669fa4a7383ef6af0830cdcf05480134783a50df3fe3e7f
    Image:         slok/sloth:v0.3.1
...
Node-Selectors:              kubernetes.io/arch=arm64
                             kubernetes.io/os=linux


$ kubectl logs sloth-7b78ffd46d-259pt
INFO[0000] Loading Kubernetes configuration...           version=v0.3.1
INFO[0000] Metrics http server listening                 addr=":8081" version=v0.3.1
INFO[0000] starting controller                           controller-id=sloth lib=kooper service=kooper.controller version=v0.3.1
```

And on AMD64:
```
$ kubectl describe pod sloth-6b8554cdd4-m8f2n
Name:         sloth-6b8554cdd4-m8f2n
Namespace:    monitoring
...
Start Time:   Mon, 14 Jun 2021 11:29:33 +0200
...
Status:       Running
...
Containers:
  sloth:
    Container ID:  containerd://cba9f3f26ffaf10d8f10d677edeb8c3dc328eb2dca7c7f2f9b901fca78df198f
    Image:         slok/sloth:v0.3.1
...
Node-Selectors:              kubernetes.io/arch=amd64
                             kubernetes.io/os=linux
                             
$ kubectl logs sloth-6b8554cdd4-m8f2n
INFO[0000] Loading Kubernetes configuration...           version=v0.3.1
INFO[0000] Metrics http server listening                 addr=":8081" version=v0.3.1
INFO[0000] starting controller                           controller-id=sloth lib=kooper service=kooper.controller version=v0.3.1
```

OT: I wrote [a small jsonnet library to deploy sloth](https://github.com/thaum-xyz/ankhmorpork/blob/master/apps/monitoring/jsonnet/lib/sloth.libsonnet). With that lib, it should be fairly easy to deploy sloth with [prometheus-operator/kube-prometheus](https://github.com/prometheus-operator/kube-prometheus) project.

**Comment by slok** [comment]
Awesome! many thanks for the tests.

I'll take a look at your `jsonnet` lib, thanks again! :tada: :1st_place_medal:
